/* Generated By:JavaCC: Do not edit this line. CalculatorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int PLUS = 3;
  /** RegularExpression Id. */
  int MINUS = 4;
  /** RegularExpression Id. */
  int MULTI = 5;
  /** RegularExpression Id. */
  int DIV = 6;
  /** RegularExpression Id. */
  int OPAR = 7;
  /** RegularExpression Id. */
  int CPAR = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<NUMBER>",
  };

}
